apiVersion: v1
kind: Pod # リソースの種類を指定する属性
metadata:
  name: simple-echo
spec: # リソースを定義するための属性
  containers:
  - name: nginx
    image: gihyodocker/nginx-proxy:latest
    env:
    - name: BACKEND_HOST
      value: localhost:8080 # echo containerのポート
    ports:
    - containerPort: 80
  - name: echo #
    image: gihyodocker/echo:latest
    ports:
    - containerPort: 8080
