apiVersion: v1
kind: Service
metadata:
  name: echo
spec:
  # type: NodePort # クラスタ外からアクセスできるService. デフォルトはClusterIP Service
  selector:
    app: echo
    # release: summer
  ports:
    - name: http
      port: 80
